Optional error color and optional okText color.
revosystems/RevoValidation pull request #4
Opened 2020-09-22 10:18 UTC by aleixgil

2020-09-23 07:28 UTC, BadChoice requested changes

2020-09-23 07:28 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +    var errorsLabelColor:UIColor?
li canviaria el nom per defaultColor

2020-09-23 07:28 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +        (color != nil) ? okTextColor = color : nil
no cal fer la comprovació pots fer directament 
`okTextColor = color` fa exactament le mateix que el que tens posat

2020-09-23 07:28 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +            initDefaultErrorsColor()
posaria tot aixo nou en una funcio que es digui `showOkColor`

2020-09-23 07:28 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +                (okTextColor != nil) ? errorsLabel?.textColor = okTextColor : nil
no cal la ternaria, ja sera nil amb l'= n'hi iha prou

2020-09-23 07:47 UTC, aleixgil commented on RevoValidation/src/Validation.swift
> +            initDefaultErrorsColor()
si vols q possi tot a dins d'una funció, tant si es defaultColor com si es okColor, he de tornar a comprovar el failed.count == 0 per assignar un color

jo crec q puder la assignació del defaultColor si, pero la del okColor ja esta bé a dins del  if failed.count == 0 tal com està, llavors la funció no shauria de dir showOkColor... a què et refereixes?

2020-09-24 07:22 UTC, BadChoice approved these changes

2020-09-24 07:22 UTC, merged