New rule: Combined rule.
revosystems/RevoValidation pull request #5
Opened 2020-10-01 15:28 UTC by aleixgil

Condition: Some rules, when one of them is passed, the combined rules are passed.
Example of use: Validation(TextField,   "containsSpecialChars+containsNumber", errorLabel)
Key identifier: "+"

2020-10-05 08:12 UTC, BadChoice requested changes

2020-10-05 08:12 UTC, BadChoice commented on RevoValidation/src/Rules.swift
>              }
a questa funcio ha quedat mass grossa amb l'if a part que esta repetit molt tros, extreu el swift del param.first fora i  així ho podras deixar sense repetir i amb una sola linia l'if i el "else"

2020-10-05 08:12 UTC, BadChoice commented on RevoValidation/src/Rules.swift
> +        guard rules.isEmpty == false else { return "" }
si la funcio es diu should, vol dir que ha de tornar un Bool, si tu tornes missatges hauria de tenir un altre nom, estil, errorMessage o algu així

2020-10-05 08:12 UTC, BadChoice commented on RevoValidation/src/Rules/RuleCombined.swift
> +    var titleTraduction:String
titleTraduction no m'agrada, title a seques millor no?

2020-10-05 08:12 UTC, BadChoice commented on RevoValidation/src/Rules/RuleCombined.swift
> +    var combinedRules:[Rule]
la classe ja es diu RuleCombined, la variable es pot dir simplement rules

2020-10-05 08:12 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +    var shouldShowFirstOneFlag:Bool = false
treu el Flag de darrere, amb el should ja sabem que es bool, per tant ja sabem que es flag

2020-10-05 08:12 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +    public func shouldShowFirstOne() -> Validation {
jo afegiria un parametre per defecte, així ho podrem posar a false si volguessim

pulic fun shouldShowFirtsOne(_ shouldShowFirstOne : Bool = true) -> Validation ...

2020-10-05 08:12 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +        shouldShowFirstOneFlag = true
self.shouldShowFirstOne = shouldShowFirstOne

2020-10-05 08:50 UTC, aleixgil commented on RevoValidation/src/Validation.swift
> +    public func shouldShowFirstOne() -> Validation {
quin sentit té posar el true o false com a parametre, si al cridar shouldShowFirstOne desde el projecte ja li estas dient q ho vols a true i sino el crides no ho fa, per tant false...?

2020-10-05 08:57 UTC, aleixgil commented on RevoValidation/src/Rules.swift
>              }
Et refereixes a encapsular el:
let params = $0.explode(":")
                switch params.first! {
                case "required"             : return RuleRequired()
                case "email"                : return RuleEmail()
                case "containsSpecialChars" : return RuleContainSpecialChars()
                case "containsNumber"       : return RuleContainsNumber()
                case "numeric"              : return RuleNumeric()
                case "length"               : return RuleLenght(Int(params.last ?? "3") ?? 3)
                case "age"                  : return RuleAge(Int(params.last ?? "18") ?? 18)
                default                     : return nil
                }
?
La cosa esta en q a self.rules es guarda la llista de rules, i en la iteració principal(compactMap), si la rule conte el "+" vol dir q hi han varies rules q es combinen i han de tornar a cridar tot el switch de la mateixa manera, iterant again....

2020-10-05 10:50 UTC, BadChoice requested changes

2020-10-05 10:50 UTC, BadChoice commented on RevoValidation/src/Rules.swift
>              }
si, pero si esta dins d'una funció quedara més endreçat

2020-10-05 10:50 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +    public func shouldShowFirstOne() -> Validation {
imaginat que fem una validation nova que te per defecte que true, (heredant) sempre es interessant poder-lo posar a false, o inclus que una rule dins sigui capaç de posar el valor a false si així fos necessàri

Ara mateix un cop l'hem posat a true no es pot desfer, de moment no ens fa falta canviarho pero així es futureproff

2020-10-06 06:50 UTC, aleixgil commented on RevoValidation/src/Validation.swift
> +    public func shouldShowFirstOne() -> Validation {
Fet!

2020-10-06 07:05 UTC, aleixgil commented
Penja versió si ho veus bé! 🙏🏽

2020-10-06 08:34 UTC, BadChoice requested changes

2020-10-06 08:34 UTC, BadChoice commented on RevoValidation/src/Rules.swift
> +            if !$0.contains("+") { return Rules.getRule($0) }
li canviaria el nom de getRule per MakeRule, els gets normalment són getters que no calculen ni creen res, en aquest cas estem construint una nova rule

2020-10-06 13:51 UTC, BadChoice approved these changes

2020-10-06 13:52 UTC, merged