Adds the option to modify rules for textField
revosystems/RevoValidation pull request #6
Opened 2022-05-26 06:58 UTC by adriamt

2022-05-26 08:55 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +    public func modifyRulesAndValidate(_ newRules : Rules){
perque serveix aixo?

2022-05-26 09:03 UTC, adriamt commented on RevoValidation/src/Validation.swift
> +    public func modifyRulesAndValidate(_ newRules : Rules){
> perque serveix aixo?

Bàsicament, per a modificar les rules, i tal com les modifica que validi el contingut. Ho necessito per a M&F que en funció del que hi hagi al prefix, la longitud del telefon sera una o altre, i el que faig es que quan es modifica el prefix, canvio les rules del telefon.

2022-05-26 10:11 UTC, draude commented on RevoValidation/src/FormValidation.swift
> +    public mutating func modifyRulesAndValidate(for field:UITextField, rules:Rules){
jo diria que aquest no cal que sigui mutating perquè no estàs modificant la "struct" oi @BadChoice ?
Potser n'hi diria updateRules i el mètode del Validation també i no fer el validar a dins d'aquí. Si mai volem modificar les "rules" sempre ens validarà i potser no ho volem.

2022-05-26 16:34 UTC, BadChoice commented on RevoValidation/src/Validation.swift
> +    public func modifyRulesAndValidate(_ newRules : Rules){
doncs jo li canviaria el nom a
```
update(rules:Rules, validate:Bool = true){

}
```

2022-05-26 16:35 UTC, BadChoice requested changes

2022-05-26 16:35 UTC, BadChoice commented on RevoValidation/src/FormValidation.swift
> +    public mutating func modifyRulesAndValidate(for field:UITextField, rules:Rules){
aqui tambe, 

update(rules:Rules, for field:UITextField, validate:Bool = true){
}

2022-05-30 10:30 UTC, BadChoice approved these changes

2022-05-30 10:30 UTC, merged